openapi: 3.0.3
info:
  title: AboutMy.email
  description: AboutMy.email
  version: 1.0.0
security:
  - BearerAuth: []
servers:
  - url: 'https://aboutmy.email/api/v1'
paths:
  /emails:
    post:
      summary: Submit new message for processing
      operationId: email
      description: Submit new message for processing
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/SubmitForm"
          application/json:
            schema:
              $ref: "#/components/schemas/Submit"
      responses:
        '200':
          description: Submitted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SubmitSuccess"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400Error"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"
      callbacks:
        progress:
          "{$request.body#progressUrl}":
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/StatusResult"
              responses:
                '200':
                  description: OK
        finished:
          "{$request.body#progressUrl}":
            post:
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      $ref: "#/components/schemas/StatusResult"
              responses:
                '200':
                  description: OK
  /emails/{resultID}:
    get:
      summary: Get status of a mail being processed
      operationId: emailStatus
      description: Get status of a mail being processed
      parameters:
        - in: path
          name: resultID
          schema:
            type: string
          required: true
          description: The result ID returned from a previous POST to /emails
      responses:
        '200':
          description: Response is being processed or has completed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResult"
        '404':
          description: Failed to find mail being processed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/400Error"
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"
  /style/content:
    post:
      summary: Upload content files
      operationId: contentPost
      description: Set whitelabel result templates
      requestBody:
        required: true
        description: files to upload
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                filename:
                  type: array
                  items:
                    type: string
                    format: binary
      responses:
        '200':
          description: Successfully uploaded files
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResult"
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"
  /style/publish:
    post:
      summary: Publish staged content
      operationId: stylePublish
      description: Publish staged content to production
      responses:
        '200':
          description: Successfully published files
        '500':
          description: Internal error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/500Error"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    Submit:
      required:
        - payload
        - from
        - to
        - ip
      properties:
        payload:
          type: string
          description: The headers and body of the message
        from:
          type: string
          format: idn-email
          description: The email address for MAIL FROM
        to:
          type: string
          format: idn-email
          description: The email address for RCPT TO
        ip:
          type: string
          format: "ip"
          description: The IP address the mail is sent from
        smtputf8:
          type: boolean
          description: Whether the email is localized
        options:
          type: string
          description: "'stage' for staged rendering"
        token:
          type: string
          description: Opaque token returned in response
        progressUrl:
          type: string
          format: uri
          description: Regular callbacks for progress messages
        finishedUrl:
          type: string
          format: uri
          description: Callback when processing is complete
    SubmitForm:
      required:
        - payload
        - from
        - to
        - ip
      properties:
        payload:
          type: string
          format: binary
          description: The headers and body of the message
        from:
          type: string
          format: idn-email
          description: The email address for MAIL FROM
        to:
          type: string
          format: idn-email
          description: The email address for RCPT TO
        ip:
          type: string
          format: "ip"
          description: The IP address the mail is sent from
        smtputf8:
          type: boolean
          description: Whether the email is localized
        options:
          type: string
          description: "'stage' for staged rendering"
        token:
          type: string
          description: Opaque token returned in response
        progressUrl:
          type: string
          format: uri
          description: Regular callbacks for progress messages
        finishedUrl:
          type: string
          format: uri
          description: Callback when processing is complete
    SubmitSuccess:
      required:
        - id
      properties:
        id:
          type: string
          description: Identifier for the result
    StatusResult:
      required:
        - id
      properties:
        id:
          type: string
          description: Identifier for the result
        url:
          type: string
          format: uri
          description: Where human readable result is available
        messages:
          type: array
          description: Zero or more processing update messages
          items:
            type: string
        token:
          type: string
          description: Opaque token copied from request
    UploadResult:
      required:
        - messages
      properties:
        messages:
          type: array
          description: Diagnostics about uploaded files
          items:
            type: string
    400Error:
      required:
        - message
      properties:
        message:
          type: string
    500Error:
      required:
        - message
      properties:
        message:
          type: string